# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\draxl\Desktop\Quardcard\CREATOR.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CREATE(object):
    def setupUi(self, CREATE):
        CREATE.setObjectName("CREATE")
        CREATE.resize(611, 575)
        CREATE.setMinimumSize(QtCore.QSize(309, 471))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        CREATE.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        CREATE.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("general/create_room.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CREATE.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(CREATE)
        self.centralwidget.setObjectName("centralwidget")
        self.header_left = QtWidgets.QLabel(self.centralwidget)
        self.header_left.setGeometry(QtCore.QRect(310, 10, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.header_left.setFont(font)
        self.header_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header_left.setAlignment(QtCore.Qt.AlignCenter)
        self.header_left.setObjectName("header_left")
        self.header_right = QtWidgets.QLabel(self.centralwidget)
        self.header_right.setGeometry(QtCore.QRect(10, 10, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.header_right.setFont(font)
        self.header_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header_right.setAlignment(QtCore.Qt.AlignCenter)
        self.header_right.setObjectName("header_right")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(290, -10, 21, 591))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.list = QtWidgets.QListWidget(self.centralwidget)
        self.list.setGeometry(QtCore.QRect(310, 50, 291, 491))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(20)
        self.list.setFont(font)
        self.list.setFrameShape(QtWidgets.QFrame.Box)
        self.list.setFrameShadow(QtWidgets.QFrame.Raised)
        self.list.setLineWidth(5)
        self.list.setDragEnabled(True)
        self.list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.list.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.list.setAlternatingRowColors(True)
        self.list.setObjectName("list")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setEnabled(True)
        self.btn_add.setGeometry(QtCore.QRect(90, 130, 121, 31))
        self.btn_add.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_add.setIcon(icon)
        self.btn_add.setIconSize(QtCore.QSize(16, 16))
        self.btn_add.setObjectName("btn_add")
        self.btn_close_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close_right.setEnabled(True)
        self.btn_close_right.setGeometry(QtCore.QRect(90, 310, 121, 31))
        self.btn_close_right.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("general/dialog_cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close_right.setIcon(icon1)
        self.btn_close_right.setIconSize(QtCore.QSize(16, 16))
        self.btn_close_right.setObjectName("btn_close_right")
        self.btn_edit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit.setEnabled(True)
        self.btn_edit.setGeometry(QtCore.QRect(90, 270, 121, 31))
        self.btn_edit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("general/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit.setIcon(icon2)
        self.btn_edit.setIconSize(QtCore.QSize(16, 16))
        self.btn_edit.setObjectName("btn_edit")
        self.type_chooser = QtWidgets.QComboBox(self.centralwidget)
        self.type_chooser.setGeometry(QtCore.QRect(40, 50, 231, 31))
        self.type_chooser.setObjectName("type_chooser")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("index_card/index_card.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.type_chooser.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("question_entry/question_entry.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.type_chooser.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("question_multiple_choice/question_multiple_choice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.type_chooser.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("question_order/question_order.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.type_chooser.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("question_radio/question_radio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.type_chooser.addItem(icon7, "")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(40, 90, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-90, 170, 391, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.header_right_2 = QtWidgets.QLabel(self.centralwidget)
        self.header_right_2.setGeometry(QtCore.QRect(10, 190, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.header_right_2.setFont(font)
        self.header_right_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header_right_2.setAlignment(QtCore.Qt.AlignCenter)
        self.header_right_2.setObjectName("header_right_2")
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setGeometry(QtCore.QRect(40, 230, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.name_edit.setFont(font)
        self.name_edit.setObjectName("name_edit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 380, 141, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("general/quardcard_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.list.raise_()
        self.header_left.raise_()
        self.header_right.raise_()
        self.line.raise_()
        self.btn_add.raise_()
        self.btn_close_right.raise_()
        self.btn_edit.raise_()
        self.type_chooser.raise_()
        self.name.raise_()
        self.line_2.raise_()
        self.header_right_2.raise_()
        self.name_edit.raise_()
        self.label.raise_()
        CREATE.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CREATE)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 21))
        self.menubar.setObjectName("menubar")
        self.menuQuardcard = QtWidgets.QMenu(self.menubar)
        self.menuQuardcard.setTitle("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("general/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuQuardcard.setIcon(icon8)
        self.menuQuardcard.setObjectName("menuQuardcard")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setTitle("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("general/open_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuInfo.setIcon(icon9)
        self.menuInfo.setObjectName("menuInfo")
        CREATE.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(CREATE)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("open_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon10)
        self.actionOpen.setObjectName("actionOpen")
        self.actionCreate = QtWidgets.QAction(CREATE)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("create_quardcard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate.setIcon(icon11)
        self.actionCreate.setObjectName("actionCreate")
        self.actionPrivate = QtWidgets.QAction(CREATE)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("singleplayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrivate.setIcon(icon12)
        self.actionPrivate.setObjectName("actionPrivate")
        self.actionCreate_Room = QtWidgets.QAction(CREATE)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("create_room.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_Room.setIcon(icon13)
        self.actionCreate_Room.setObjectName("actionCreate_Room")
        self.actionJoin_Room = QtWidgets.QAction(CREATE)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("search_room.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJoin_Room.setIcon(icon14)
        self.actionJoin_Room.setObjectName("actionJoin_Room")
        self.actionAbout = QtWidgets.QAction(CREATE)
        self.actionAbout.setIcon(icon9)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSaveproject = QtWidgets.QAction(CREATE)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("general/creator_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveproject.setIcon(icon15)
        self.actionSaveproject.setObjectName("actionSaveproject")
        self.actionOpenproject = QtWidgets.QAction(CREATE)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("general/open_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenproject.setIcon(icon16)
        self.actionOpenproject.setObjectName("actionOpenproject")
        self.actionNewproject = QtWidgets.QAction(CREATE)
        self.actionNewproject.setIcon(icon)
        self.actionNewproject.setObjectName("actionNewproject")
        self.menuQuardcard.addAction(self.actionNewproject)
        self.menuQuardcard.addAction(self.actionOpenproject)
        self.menuQuardcard.addAction(self.actionSaveproject)
        self.menuQuardcard.addSeparator()
        self.menuInfo.addAction(self.actionAbout)
        self.menubar.addAction(self.menuQuardcard.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(CREATE)
        QtCore.QMetaObject.connectSlotsByName(CREATE)
        CREATE.setTabOrder(self.list, self.btn_add)
        CREATE.setTabOrder(self.btn_add, self.btn_edit)
        CREATE.setTabOrder(self.btn_edit, self.type_chooser)
        CREATE.setTabOrder(self.type_chooser, self.name)
        CREATE.setTabOrder(self.name, self.btn_close_right)

    def retranslateUi(self, CREATE):
        _translate = QtCore.QCoreApplication.translate
        CREATE.setWindowTitle(_translate("CREATE", "Create"))
        self.header_left.setText(_translate("CREATE", "Questions"))
        self.header_right.setText(_translate("CREATE", "Create"))
        self.btn_add.setText(_translate("CREATE", " Add"))
        self.btn_add.setShortcut(_translate("CREATE", "Ctrl+A"))
        self.btn_close_right.setToolTip(_translate("CREATE", "<html><head/><body><p><span style=\" font-weight:600;\">DEL</span></p><p>remove question</p></body></html>"))
        self.btn_close_right.setText(_translate("CREATE", " Remove"))
        self.btn_close_right.setShortcut(_translate("CREATE", "Del"))
        self.btn_edit.setToolTip(_translate("CREATE", "<html><head/><body><p>edit question</p></body></html>"))
        self.btn_edit.setText(_translate("CREATE", " Edit"))
        self.btn_edit.setShortcut(_translate("CREATE", "Ctrl+E"))
        self.type_chooser.setToolTip(_translate("CREATE", "<html><head/><body><p>type of question</p></body></html>"))
        self.type_chooser.setItemText(0, _translate("CREATE", "Index Card"))
        self.type_chooser.setItemText(1, _translate("CREATE", "Question + Entry"))
        self.type_chooser.setItemText(2, _translate("CREATE", "Question + Multiple Choice"))
        self.type_chooser.setItemText(3, _translate("CREATE", "Question + Order"))
        self.type_chooser.setItemText(4, _translate("CREATE", "Question + Radio"))
        self.name.setPlaceholderText(_translate("CREATE", "Name"))
        self.header_right_2.setText(_translate("CREATE", "Edit"))
        self.name_edit.setPlaceholderText(_translate("CREATE", "Name"))
        self.actionOpen.setText(_translate("CREATE", "Open"))
        self.actionCreate.setText(_translate("CREATE", "Create"))
        self.actionPrivate.setText(_translate("CREATE", "Private"))
        self.actionCreate_Room.setText(_translate("CREATE", "Create Room"))
        self.actionJoin_Room.setText(_translate("CREATE", "Connect Room"))
        self.actionAbout.setText(_translate("CREATE", "About"))
        self.actionSaveproject.setText(_translate("CREATE", "Save"))
        self.actionOpenproject.setText(_translate("CREATE", "Open"))
        self.actionNewproject.setText(_translate("CREATE", "New"))

