# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\draxl\Desktop\Quardcard\MAINWINDOW.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MAINWINDOW(object):
    def setupUi(self, MAINWINDOW):
        MAINWINDOW.setObjectName("MAINWINDOW")
        MAINWINDOW.resize(642, 465)
        MAINWINDOW.setMinimumSize(QtCore.QSize(642, 465))
        MAINWINDOW.setMaximumSize(QtCore.QSize(940, 465))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MAINWINDOW.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        MAINWINDOW.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("general/quardcard_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MAINWINDOW.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MAINWINDOW)
        self.centralwidget.setObjectName("centralwidget")
        self.progressbar_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.progressbar_progress.setEnabled(True)
        self.progressbar_progress.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.progressbar_progress.setFont(font)
        self.progressbar_progress.setMaximum(0)
        self.progressbar_progress.setObjectName("progressbar_progress")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(-40, 40, 981, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_1.setGeometry(QtCore.QRect(200, -13, 20, 61))
        self.line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setEnabled(False)
        self.btn_next.setGeometry(QtCore.QRect(511, 10, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_next.setFont(font)
        self.btn_next.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_next.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("general/button_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon1)
        self.btn_next.setIconSize(QtCore.QSize(16, 16))
        self.btn_next.setAutoRepeatInterval(150)
        self.btn_next.setFlat(True)
        self.btn_next.setObjectName("btn_next")
        self.btn_previous = QtWidgets.QPushButton(self.centralwidget)
        self.btn_previous.setEnabled(False)
        self.btn_previous.setGeometry(QtCore.QRect(420, 10, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_previous.setFont(font)
        self.btn_previous.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_previous.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("general/button_previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_previous.setIcon(icon2)
        self.btn_previous.setIconSize(QtCore.QSize(16, 16))
        self.btn_previous.setAutoRepeatInterval(150)
        self.btn_previous.setFlat(True)
        self.btn_previous.setObjectName("btn_previous")
        self.index_card_obj = QtWidgets.QWidget(self.centralwidget)
        self.index_card_obj.setGeometry(QtCore.QRect(0, 50, 641, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.index_card_obj.sizePolicy().hasHeightForWidth())
        self.index_card_obj.setSizePolicy(sizePolicy)
        self.index_card_obj.setAutoFillBackground(False)
        self.index_card_obj.setObjectName("index_card_obj")
        self.index_card_obj_btn = QtWidgets.QPushButton(self.index_card_obj)
        self.index_card_obj_btn.setEnabled(True)
        self.index_card_obj_btn.setGeometry(QtCore.QRect(470, 10, 161, 371))
        self.index_card_obj_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.index_card_obj_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("index_card/index_card_turn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.index_card_obj_btn.setIcon(icon3)
        self.index_card_obj_btn.setIconSize(QtCore.QSize(130, 130))
        self.index_card_obj_btn.setObjectName("index_card_obj_btn")
        self.index_card_obj_card = QtWidgets.QLabel(self.index_card_obj)
        self.index_card_obj_card.setGeometry(QtCore.QRect(10, 10, 451, 371))
        font = QtGui.QFont()
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.index_card_obj_card.setFont(font)
        self.index_card_obj_card.setFocusPolicy(QtCore.Qt.NoFocus)
        self.index_card_obj_card.setAutoFillBackground(True)
        self.index_card_obj_card.setFrameShape(QtWidgets.QFrame.Box)
        self.index_card_obj_card.setFrameShadow(QtWidgets.QFrame.Raised)
        self.index_card_obj_card.setLineWidth(5)
        self.index_card_obj_card.setMidLineWidth(5)
        self.index_card_obj_card.setAlignment(QtCore.Qt.AlignCenter)
        self.index_card_obj_card.setWordWrap(True)
        self.index_card_obj_card.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.index_card_obj_card.setObjectName("index_card_obj_card")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(370, -13, 20, 61))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.btn_previous_fav = QtWidgets.QPushButton(self.centralwidget)
        self.btn_previous_fav.setEnabled(False)
        self.btn_previous_fav.setGeometry(QtCore.QRect(390, 10, 31, 31))
        self.btn_previous_fav.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("general/button_previous_nonanswerd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_previous_fav.setIcon(icon4)
        self.btn_previous_fav.setFlat(True)
        self.btn_previous_fav.setObjectName("btn_previous_fav")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(-86, 48, 731, 401))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("bg/bg.png"))
        self.bg.setObjectName("bg")
        self.question_entry = QtWidgets.QWidget(self.centralwidget)
        self.question_entry.setGeometry(QtCore.QRect(0, 50, 641, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_entry.sizePolicy().hasHeightForWidth())
        self.question_entry.setSizePolicy(sizePolicy)
        self.question_entry.setAutoFillBackground(False)
        self.question_entry.setObjectName("question_entry")
        self.question_entry_question = QtWidgets.QPlainTextEdit(self.question_entry)
        self.question_entry_question.setGeometry(QtCore.QRect(10, 10, 621, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.question_entry_question.setFont(font)
        self.question_entry_question.setReadOnly(True)
        self.question_entry_question.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.question_entry_question.setObjectName("question_entry_question")
        self.question_entry_test = QtWidgets.QPushButton(self.question_entry)
        self.question_entry_test.setEnabled(True)
        self.question_entry_test.setGeometry(QtCore.QRect(280, 350, 91, 31))
        self.question_entry_test.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.question_entry_test.setAutoFillBackground(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("general/start_quardcard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.question_entry_test.setIcon(icon5)
        self.question_entry_test.setIconSize(QtCore.QSize(30, 30))
        self.question_entry_test.setObjectName("question_entry_test")
        self.question_entry_input_field = QtWidgets.QPlainTextEdit(self.question_entry)
        self.question_entry_input_field.setGeometry(QtCore.QRect(10, 90, 621, 241))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.question_entry_input_field.setFont(font)
        self.question_entry_input_field.setObjectName("question_entry_input_field")
        self.question_muliple_choice = QtWidgets.QWidget(self.centralwidget)
        self.question_muliple_choice.setGeometry(QtCore.QRect(0, 50, 641, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_muliple_choice.sizePolicy().hasHeightForWidth())
        self.question_muliple_choice.setSizePolicy(sizePolicy)
        self.question_muliple_choice.setAutoFillBackground(False)
        self.question_muliple_choice.setObjectName("question_muliple_choice")
        self.question_muliple_choice_question = QtWidgets.QPlainTextEdit(self.question_muliple_choice)
        self.question_muliple_choice_question.setGeometry(QtCore.QRect(10, 10, 621, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.question_muliple_choice_question.setFont(font)
        self.question_muliple_choice_question.setReadOnly(True)
        self.question_muliple_choice_question.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.question_muliple_choice_question.setObjectName("question_muliple_choice_question")
        self.question_muliple_choice_checkbox_1 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_1.setGeometry(QtCore.QRect(20, 100, 301, 21))
        self.question_muliple_choice_checkbox_1.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_1.setObjectName("question_muliple_choice_checkbox_1")
        self.question_muliple_choice_checkbox_10 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_10.setGeometry(QtCore.QRect(330, 220, 301, 22))
        self.question_muliple_choice_checkbox_10.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_10.setObjectName("question_muliple_choice_checkbox_10")
        self.question_muliple_choice_checkbox_8 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_8.setGeometry(QtCore.QRect(330, 190, 301, 22))
        self.question_muliple_choice_checkbox_8.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_8.setObjectName("question_muliple_choice_checkbox_8")
        self.question_muliple_choice_checkbox_6 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_6.setGeometry(QtCore.QRect(330, 160, 301, 22))
        self.question_muliple_choice_checkbox_6.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_6.setObjectName("question_muliple_choice_checkbox_6")
        self.question_muliple_choice_checkbox_4 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_4.setGeometry(QtCore.QRect(330, 130, 301, 22))
        self.question_muliple_choice_checkbox_4.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_4.setObjectName("question_muliple_choice_checkbox_4")
        self.question_muliple_choice_checkbox_7 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_7.setGeometry(QtCore.QRect(20, 190, 301, 22))
        self.question_muliple_choice_checkbox_7.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_7.setObjectName("question_muliple_choice_checkbox_7")
        self.question_muliple_choice_checkbox_9 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_9.setGeometry(QtCore.QRect(20, 220, 301, 22))
        self.question_muliple_choice_checkbox_9.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_9.setObjectName("question_muliple_choice_checkbox_9")
        self.question_muliple_choice_checkbox_11 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_11.setGeometry(QtCore.QRect(20, 250, 301, 22))
        self.question_muliple_choice_checkbox_11.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_11.setObjectName("question_muliple_choice_checkbox_11")
        self.question_muliple_choice_checkbox_5 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_5.setGeometry(QtCore.QRect(20, 160, 301, 22))
        self.question_muliple_choice_checkbox_5.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_5.setObjectName("question_muliple_choice_checkbox_5")
        self.question_muliple_choice_checkbox_3 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_3.setGeometry(QtCore.QRect(20, 130, 301, 22))
        self.question_muliple_choice_checkbox_3.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_3.setObjectName("question_muliple_choice_checkbox_3")
        self.question_muliple_choice_checkbox_2 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_2.setGeometry(QtCore.QRect(330, 100, 301, 22))
        self.question_muliple_choice_checkbox_2.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_2.setObjectName("question_muliple_choice_checkbox_2")
        self.question_muliple_choice_checkbox_12 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_12.setGeometry(QtCore.QRect(330, 250, 301, 22))
        self.question_muliple_choice_checkbox_12.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_12.setObjectName("question_muliple_choice_checkbox_12")
        self.question_muliple_choice_checkbox_13 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_13.setGeometry(QtCore.QRect(20, 280, 301, 22))
        self.question_muliple_choice_checkbox_13.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_13.setObjectName("question_muliple_choice_checkbox_13")
        self.question_muliple_choice_checkbox_15 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_15.setGeometry(QtCore.QRect(20, 310, 301, 22))
        self.question_muliple_choice_checkbox_15.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_15.setObjectName("question_muliple_choice_checkbox_15")
        self.question_muliple_choice_checkbox_16 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_16.setGeometry(QtCore.QRect(330, 310, 301, 22))
        self.question_muliple_choice_checkbox_16.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_16.setObjectName("question_muliple_choice_checkbox_16")
        self.question_muliple_choice_checkbox_14 = QtWidgets.QCheckBox(self.question_muliple_choice)
        self.question_muliple_choice_checkbox_14.setGeometry(QtCore.QRect(330, 280, 301, 22))
        self.question_muliple_choice_checkbox_14.setAutoFillBackground(True)
        self.question_muliple_choice_checkbox_14.setObjectName("question_muliple_choice_checkbox_14")
        self.question_muliple_choice_test = QtWidgets.QPushButton(self.question_muliple_choice)
        self.question_muliple_choice_test.setEnabled(True)
        self.question_muliple_choice_test.setGeometry(QtCore.QRect(280, 350, 91, 31))
        self.question_muliple_choice_test.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.question_muliple_choice_test.setAutoFillBackground(False)
        self.question_muliple_choice_test.setIcon(icon5)
        self.question_muliple_choice_test.setIconSize(QtCore.QSize(30, 30))
        self.question_muliple_choice_test.setObjectName("question_muliple_choice_test")
        self.question_radio = QtWidgets.QWidget(self.centralwidget)
        self.question_radio.setGeometry(QtCore.QRect(0, 50, 641, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_radio.sizePolicy().hasHeightForWidth())
        self.question_radio.setSizePolicy(sizePolicy)
        self.question_radio.setAutoFillBackground(False)
        self.question_radio.setObjectName("question_radio")
        self.question_radio_checkbox_question = QtWidgets.QPlainTextEdit(self.question_radio)
        self.question_radio_checkbox_question.setGeometry(QtCore.QRect(10, 10, 621, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.question_radio_checkbox_question.setFont(font)
        self.question_radio_checkbox_question.setReadOnly(True)
        self.question_radio_checkbox_question.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.question_radio_checkbox_question.setObjectName("question_radio_checkbox_question")
        self.question_radio_checkbox_1 = QtWidgets.QRadioButton(self.question_radio)
        self.question_radio_checkbox_1.setGeometry(QtCore.QRect(10, 100, 621, 21))
        self.question_radio_checkbox_1.setAutoFillBackground(True)
        self.question_radio_checkbox_1.setObjectName("question_radio_checkbox_1")
        self.question_radio_checkbox_2 = QtWidgets.QRadioButton(self.question_radio)
        self.question_radio_checkbox_2.setGeometry(QtCore.QRect(10, 130, 621, 22))
        self.question_radio_checkbox_2.setAutoFillBackground(True)
        self.question_radio_checkbox_2.setObjectName("question_radio_checkbox_2")
        self.question_radio_checkbox_4 = QtWidgets.QRadioButton(self.question_radio)
        self.question_radio_checkbox_4.setGeometry(QtCore.QRect(10, 190, 621, 21))
        self.question_radio_checkbox_4.setAutoFillBackground(True)
        self.question_radio_checkbox_4.setObjectName("question_radio_checkbox_4")
        self.question_radio_checkbox_3 = QtWidgets.QRadioButton(self.question_radio)
        self.question_radio_checkbox_3.setGeometry(QtCore.QRect(10, 160, 621, 22))
        self.question_radio_checkbox_3.setAutoFillBackground(True)
        self.question_radio_checkbox_3.setObjectName("question_radio_checkbox_3")
        self.question_radio_checkbox_test = QtWidgets.QPushButton(self.question_radio)
        self.question_radio_checkbox_test.setEnabled(True)
        self.question_radio_checkbox_test.setGeometry(QtCore.QRect(280, 230, 91, 31))
        self.question_radio_checkbox_test.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.question_radio_checkbox_test.setAutoFillBackground(False)
        self.question_radio_checkbox_test.setIcon(icon5)
        self.question_radio_checkbox_test.setIconSize(QtCore.QSize(30, 30))
        self.question_radio_checkbox_test.setObjectName("question_radio_checkbox_test")
        self.question_order = QtWidgets.QWidget(self.centralwidget)
        self.question_order.setGeometry(QtCore.QRect(0, 50, 641, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_order.sizePolicy().hasHeightForWidth())
        self.question_order.setSizePolicy(sizePolicy)
        self.question_order.setObjectName("question_order")
        self.question_order_question = QtWidgets.QPlainTextEdit(self.question_order)
        self.question_order_question.setGeometry(QtCore.QRect(10, 10, 621, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.question_order_question.setFont(font)
        self.question_order_question.setReadOnly(True)
        self.question_order_question.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.question_order_question.setObjectName("question_order_question")
        self.question_order_test = QtWidgets.QPushButton(self.question_order)
        self.question_order_test.setEnabled(True)
        self.question_order_test.setGeometry(QtCore.QRect(280, 330, 91, 31))
        self.question_order_test.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.question_order_test.setAutoFillBackground(False)
        self.question_order_test.setIcon(icon5)
        self.question_order_test.setIconSize(QtCore.QSize(30, 30))
        self.question_order_test.setObjectName("question_order_test")
        self.question_order_list = QtWidgets.QListWidget(self.question_order)
        self.question_order_list.setGeometry(QtCore.QRect(10, 100, 621, 192))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(20)
        self.question_order_list.setFont(font)
        self.question_order_list.setDragEnabled(True)
        self.question_order_list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.question_order_list.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.question_order_list.setAlternatingRowColors(True)
        self.question_order_list.setObjectName("question_order_list")
        item = QtWidgets.QListWidgetItem()
        self.question_order_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_order_list.addItem(item)
        self.btn_up = QtWidgets.QPushButton(self.question_order)
        self.btn_up.setGeometry(QtCore.QRect(10, 300, 81, 31))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("question_order/question_order_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_up.setIcon(icon6)
        self.btn_up.setObjectName("btn_up")
        self.btn_down = QtWidgets.QPushButton(self.question_order)
        self.btn_down.setGeometry(QtCore.QRect(10, 340, 81, 31))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("question_order/question_order_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_down.setIcon(icon7)
        self.btn_down.setObjectName("btn_down")
        self.unsupported_question = QtWidgets.QWidget(self.centralwidget)
        self.unsupported_question.setGeometry(QtCore.QRect(0, 50, 641, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unsupported_question.sizePolicy().hasHeightForWidth())
        self.unsupported_question.setSizePolicy(sizePolicy)
        self.unsupported_question.setAutoFillBackground(False)
        self.unsupported_question.setObjectName("unsupported_question")
        self.unsupported_question_picture = QtWidgets.QLabel(self.unsupported_question)
        self.unsupported_question_picture.setGeometry(QtCore.QRect(250, 90, 141, 141))
        self.unsupported_question_picture.setText("")
        self.unsupported_question_picture.setPixmap(QtGui.QPixmap("unsupported/warning.png"))
        self.unsupported_question_picture.setObjectName("unsupported_question_picture")
        self.unsupported_question_label = QtWidgets.QLabel(self.unsupported_question)
        self.unsupported_question_label.setGeometry(QtCore.QRect(120, 240, 391, 20))
        self.unsupported_question_label.setAutoFillBackground(True)
        self.unsupported_question_label.setAlignment(QtCore.Qt.AlignCenter)
        self.unsupported_question_label.setObjectName("unsupported_question_label")
        self.preload = QtWidgets.QWidget(self.centralwidget)
        self.preload.setGeometry(QtCore.QRect(0, 50, 641, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preload.sizePolicy().hasHeightForWidth())
        self.preload.setSizePolicy(sizePolicy)
        self.preload.setAutoFillBackground(False)
        self.preload.setObjectName("preload")
        self.preload_pic = QtWidgets.QLabel(self.preload)
        self.preload_pic.setGeometry(QtCore.QRect(250, 90, 141, 141))
        self.preload_pic.setText("")
        self.preload_pic.setPixmap(QtGui.QPixmap("start_question/start.png"))
        self.preload_pic.setObjectName("preload_pic")
        self.preload_label = QtWidgets.QLabel(self.preload)
        self.preload_label.setGeometry(QtCore.QRect(120, 240, 391, 20))
        self.preload_label.setAutoFillBackground(True)
        self.preload_label.setAlignment(QtCore.Qt.AlignCenter)
        self.preload_label.setObjectName("preload_label")
        self.btn_next_fav = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next_fav.setEnabled(False)
        self.btn_next_fav.setGeometry(QtCore.QRect(600, 10, 31, 31))
        self.btn_next_fav.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("general/button_next_nonanswerd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next_fav.setIcon(icon8)
        self.btn_next_fav.setFlat(True)
        self.btn_next_fav.setObjectName("btn_next_fav")
        self.bg_wide = QtWidgets.QLabel(self.centralwidget)
        self.bg_wide.setEnabled(True)
        self.bg_wide.setGeometry(QtCore.QRect(-10, 0, 951, 451))
        self.bg_wide.setText("")
        self.bg_wide.setPixmap(QtGui.QPixmap("bg/bg_btn.jpg"))
        self.bg_wide.setScaledContents(False)
        self.bg_wide.setAlignment(QtCore.Qt.AlignCenter)
        self.bg_wide.setObjectName("bg_wide")
        self.cash_mode = QtWidgets.QWidget(self.centralwidget)
        self.cash_mode.setGeometry(QtCore.QRect(209, -1, 171, 51))
        self.cash_mode.setObjectName("cash_mode")
        self.label_2 = QtWidgets.QLabel(self.cash_mode)
        self.label_2.setGeometry(QtCore.QRect(130, 10, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("general/cash.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.lcd_score = QtWidgets.QLabel(self.cash_mode)
        self.lcd_score.setGeometry(QtCore.QRect(0, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lcd_score.setFont(font)
        self.lcd_score.setAutoFillBackground(False)
        self.lcd_score.setStyleSheet("color: rgb(255, 215, 0);")
        self.lcd_score.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lcd_score.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_score.setScaledContents(False)
        self.lcd_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lcd_score.setObjectName("lcd_score")
        self.time_mode = QtWidgets.QWidget(self.centralwidget)
        self.time_mode.setEnabled(True)
        self.time_mode.setGeometry(QtCore.QRect(210, 0, 171, 51))
        self.time_mode.setObjectName("time_mode")
        self.label_4 = QtWidgets.QLabel(self.time_mode)
        self.label_4.setGeometry(QtCore.QRect(130, 10, 31, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("general/clock.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.lcd_time = QtWidgets.QLabel(self.time_mode)
        self.lcd_time.setGeometry(QtCore.QRect(0, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lcd_time.setFont(font)
        self.lcd_time.setAutoFillBackground(False)
        self.lcd_time.setStyleSheet("color: rgb(156, 39, 176);")
        self.lcd_time.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lcd_time.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_time.setScaledContents(False)
        self.lcd_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lcd_time.setObjectName("lcd_time")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(540, 430, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_liveedit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_liveedit.setEnabled(False)
        self.btn_liveedit.setGeometry(QtCore.QRect(900, 10, 31, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_liveedit.setFont(font)
        self.btn_liveedit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_liveedit.setAutoFillBackground(False)
        self.btn_liveedit.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("general/live_edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_liveedit.setIcon(icon9)
        self.btn_liveedit.setIconSize(QtCore.QSize(25, 25))
        self.btn_liveedit.setFlat(True)
        self.btn_liveedit.setObjectName("btn_liveedit")
        self.btn_fav = QtWidgets.QPushButton(self.centralwidget)
        self.btn_fav.setEnabled(False)
        self.btn_fav.setGeometry(QtCore.QRect(650, 10, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_fav.setFont(font)
        self.btn_fav.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_fav.setAutoFillBackground(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("general/favourite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_fav.setIcon(icon10)
        self.btn_fav.setIconSize(QtCore.QSize(25, 25))
        self.btn_fav.setCheckable(True)
        self.btn_fav.setFlat(True)
        self.btn_fav.setObjectName("btn_fav")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(630, -13, 31, 461))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.list_questions = QtWidgets.QListWidget(self.centralwidget)
        self.list_questions.setEnabled(False)
        self.list_questions.setGeometry(QtCore.QRect(652, 56, 281, 381))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(18)
        self.list_questions.setFont(font)
        self.list_questions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_questions.setProperty("showDropIndicator", False)
        self.list_questions.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.list_questions.setAlternatingRowColors(True)
        self.list_questions.setObjectName("list_questions")
        self.btn_show_answers = QtWidgets.QPushButton(self.centralwidget)
        self.btn_show_answers.setEnabled(False)
        self.btn_show_answers.setGeometry(QtCore.QRect(760, 10, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_show_answers.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("general/show_answers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_show_answers.setIcon(icon11)
        self.btn_show_answers.setFlat(True)
        self.btn_show_answers.setObjectName("btn_show_answers")
        self.question_radio.raise_()
        self.question_order.raise_()
        self.question_muliple_choice.raise_()
        self.preload.raise_()
        self.unsupported_question.raise_()
        self.question_entry.raise_()
        self.index_card_obj.raise_()
        self.bg_wide.raise_()
        self.btn_next.raise_()
        self.btn_next_fav.raise_()
        self.btn_previous_fav.raise_()
        self.line_1.raise_()
        self.progressbar_progress.raise_()
        self.line_2.raise_()
        self.btn_liveedit.raise_()
        self.btn_fav.raise_()
        self.line_3.raise_()
        self.list_questions.raise_()
        self.line_4.raise_()
        self.cash_mode.raise_()
        self.time_mode.raise_()
        self.btn_previous.raise_()
        self.bg.raise_()
        self.btn_show_answers.raise_()
        self.label_5.raise_()
        MAINWINDOW.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MAINWINDOW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 28))
        self.menubar.setStyleSheet("font: 25 14pt \"Calibri Light\";\n"
"background-color: rgb(68, 68, 68);")
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuQuardcard = QtWidgets.QMenu(self.menubar)
        self.menuQuardcard.setTitle("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("general/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuQuardcard.setIcon(icon12)
        self.menuQuardcard.setObjectName("menuQuardcard")
        self.menuGo = QtWidgets.QMenu(self.menubar)
        self.menuGo.setTitle("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("start_question/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuGo.setIcon(icon13)
        self.menuGo.setObjectName("menuGo")
        self.menuPrivate = QtWidgets.QMenu(self.menuGo)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("general/singleplayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuPrivate.setIcon(icon14)
        self.menuPrivate.setObjectName("menuPrivate")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setTitle("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("general/open_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuInfo.setIcon(icon15)
        self.menuInfo.setObjectName("menuInfo")
        MAINWINDOW.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MAINWINDOW)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("general/open_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon16)
        self.actionOpen.setObjectName("actionOpen")
        self.actionCreate = QtWidgets.QAction(MAINWINDOW)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("general/create_room.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate.setIcon(icon17)
        self.actionCreate.setObjectName("actionCreate")
        self.actionCreate_Room = QtWidgets.QAction(MAINWINDOW)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("create_room.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_Room.setIcon(icon18)
        self.actionCreate_Room.setObjectName("actionCreate_Room")
        self.actionJoin_Room = QtWidgets.QAction(MAINWINDOW)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("search_room.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJoin_Room.setIcon(icon19)
        self.actionJoin_Room.setObjectName("actionJoin_Room")
        self.actionAbout = QtWidgets.QAction(MAINWINDOW)
        self.actionAbout.setIcon(icon15)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNormal = QtWidgets.QAction(MAINWINDOW)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("general/singleplayer_normal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNormal.setIcon(icon20)
        self.actionNormal.setObjectName("actionNormal")
        self.actionExit = QtWidgets.QAction(MAINWINDOW)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("general/dialog_cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon21)
        self.actionExit.setObjectName("actionExit")
        self.actionTime = QtWidgets.QAction(MAINWINDOW)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("general/singleplayer_time.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTime.setIcon(icon22)
        self.actionTime.setObjectName("actionTime")
        self.actionSettings = QtWidgets.QAction(MAINWINDOW)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("general/dialog_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon23)
        self.actionSettings.setObjectName("actionSettings")
        self.actionBreak = QtWidgets.QAction(MAINWINDOW)
        self.actionBreak.setIcon(icon21)
        self.actionBreak.setObjectName("actionBreak")
        self.menuQuardcard.addAction(self.actionOpen)
        self.menuQuardcard.addAction(self.actionCreate)
        self.menuQuardcard.addAction(self.actionExit)
        self.menuPrivate.addAction(self.actionNormal)
        self.menuPrivate.addAction(self.actionTime)
        self.menuGo.addAction(self.menuPrivate.menuAction())
        self.menuGo.addAction(self.actionBreak)
        self.menuInfo.addAction(self.actionAbout)
        self.menuInfo.addAction(self.actionSettings)
        self.menubar.addAction(self.menuQuardcard.menuAction())
        self.menubar.addAction(self.menuGo.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MAINWINDOW)
        QtCore.QMetaObject.connectSlotsByName(MAINWINDOW)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_1, self.question_muliple_choice_checkbox_2)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_2, self.question_muliple_choice_checkbox_3)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_3, self.question_muliple_choice_checkbox_4)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_4, self.question_muliple_choice_checkbox_5)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_5, self.question_muliple_choice_checkbox_6)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_6, self.question_muliple_choice_checkbox_7)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_7, self.question_muliple_choice_checkbox_8)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_8, self.question_muliple_choice_checkbox_9)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_9, self.question_muliple_choice_checkbox_10)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_10, self.question_muliple_choice_checkbox_11)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_11, self.question_muliple_choice_checkbox_12)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_12, self.question_muliple_choice_checkbox_13)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_13, self.question_muliple_choice_checkbox_14)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_14, self.question_muliple_choice_checkbox_15)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_15, self.question_muliple_choice_checkbox_16)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_checkbox_16, self.question_entry_test)
        MAINWINDOW.setTabOrder(self.question_entry_test, self.btn_previous_fav)
        MAINWINDOW.setTabOrder(self.btn_previous_fav, self.btn_previous)
        MAINWINDOW.setTabOrder(self.btn_previous, self.question_entry_question)
        MAINWINDOW.setTabOrder(self.question_entry_question, self.index_card_obj_btn)
        MAINWINDOW.setTabOrder(self.index_card_obj_btn, self.btn_next)
        MAINWINDOW.setTabOrder(self.btn_next, self.question_muliple_choice_question)
        MAINWINDOW.setTabOrder(self.question_muliple_choice_question, self.question_entry_input_field)
        MAINWINDOW.setTabOrder(self.question_entry_input_field, self.question_muliple_choice_test)

    def retranslateUi(self, MAINWINDOW):
        _translate = QtCore.QCoreApplication.translate
        MAINWINDOW.setWindowTitle(_translate("MAINWINDOW", "quardcard"))
        self.progressbar_progress.setFormat(_translate("MAINWINDOW", "Question %v of %m"))
        self.btn_next.setToolTip(_translate("MAINWINDOW", "<html><head/><body><p>RIGTH</p><p>go to the next question</p></body></html>"))
        self.btn_next.setText(_translate("MAINWINDOW", " Next"))
        self.btn_next.setShortcut(_translate("MAINWINDOW", "Right"))
        self.btn_previous.setToolTip(_translate("MAINWINDOW", "<html><head/><body><p>LEFT</p><p>go to the previous question</p></body></html>"))
        self.btn_previous.setText(_translate("MAINWINDOW", " Before"))
        self.btn_previous.setShortcut(_translate("MAINWINDOW", "Left"))
        self.index_card_obj_btn.setShortcut(_translate("MAINWINDOW", "Space"))
        self.index_card_obj_card.setText(_translate("MAINWINDOW", "Hello World"))
        self.btn_previous_fav.setToolTip(_translate("MAINWINDOW", "Jump to the last unanswered question"))
        self.question_entry_question.setPlainText(_translate("MAINWINDOW", "Text Question"))
        self.question_entry_test.setToolTip(_translate("MAINWINDOW", "<html><head/><body><p>checks the answer</p></body></html>"))
        self.question_entry_test.setText(_translate("MAINWINDOW", " Test"))
        self.question_entry_input_field.setPlaceholderText(_translate("MAINWINDOW", "Your answer goes here..."))
        self.question_muliple_choice_question.setPlainText(_translate("MAINWINDOW", "Multiple Choice Question"))
        self.question_muliple_choice_checkbox_1.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_10.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_8.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_6.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_4.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_7.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_9.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_11.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_5.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_3.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_2.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_12.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_13.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_15.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_16.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_checkbox_14.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_muliple_choice_test.setToolTip(_translate("MAINWINDOW", "<html><head/><body><p>checks the answer</p></body></html>"))
        self.question_muliple_choice_test.setText(_translate("MAINWINDOW", " Test"))
        self.question_radio_checkbox_question.setPlainText(_translate("MAINWINDOW", "Radio Question"))
        self.question_radio_checkbox_1.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_radio_checkbox_2.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_radio_checkbox_4.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_radio_checkbox_3.setText(_translate("MAINWINDOW", "CheckBox"))
        self.question_radio_checkbox_test.setToolTip(_translate("MAINWINDOW", "<html><head/><body><p>checks the answer</p></body></html>"))
        self.question_radio_checkbox_test.setText(_translate("MAINWINDOW", " Test"))
        self.question_order_question.setPlainText(_translate("MAINWINDOW", "Order Question"))
        self.question_order_test.setToolTip(_translate("MAINWINDOW", "<html><head/><body><p>checks the answer</p></body></html>"))
        self.question_order_test.setText(_translate("MAINWINDOW", " Test"))
        __sortingEnabled = self.question_order_list.isSortingEnabled()
        self.question_order_list.setSortingEnabled(False)
        item = self.question_order_list.item(0)
        item.setText(_translate("MAINWINDOW", "Item1"))
        item = self.question_order_list.item(1)
        item.setText(_translate("MAINWINDOW", "Item2"))
        self.question_order_list.setSortingEnabled(__sortingEnabled)
        self.btn_up.setText(_translate("MAINWINDOW", " Up"))
        self.btn_up.setShortcut(_translate("MAINWINDOW", "Up"))
        self.btn_down.setText(_translate("MAINWINDOW", " Down"))
        self.btn_down.setShortcut(_translate("MAINWINDOW", "Down"))
        self.unsupported_question_label.setText(_translate("MAINWINDOW", "Unsupported Question"))
        self.preload_label.setText(_translate("MAINWINDOW", "One more step and your quardcard will start."))
        self.btn_next_fav.setToolTip(_translate("MAINWINDOW", "<html><head/><body><p>Jump to the last unanswered question</p></body></html>"))
        self.lcd_score.setText(_translate("MAINWINDOW", "0"))
        self.lcd_time.setText(_translate("MAINWINDOW", "30"))
        self.label_5.setText(_translate("MAINWINDOW", "Drag for more info ->"))
        self.btn_liveedit.setToolTip(_translate("MAINWINDOW", "<html><head/><body><p>edit the question-library, only if know what you\'re doing!</p></body></html>"))
        self.btn_fav.setToolTip(_translate("MAINWINDOW", "<html><head/><body><p>add question to favourite</p></body></html>"))
        self.btn_fav.setText(_translate("MAINWINDOW", "Favourite"))
        self.btn_show_answers.setToolTip(_translate("MAINWINDOW", "<html><head/><body><p>Show the answer</p></body></html>"))
        self.btn_show_answers.setText(_translate("MAINWINDOW", "Show answers"))
        self.menuPrivate.setTitle(_translate("MAINWINDOW", "Private"))
        self.actionOpen.setText(_translate("MAINWINDOW", "Open"))
        self.actionCreate.setText(_translate("MAINWINDOW", "Create"))
        self.actionCreate_Room.setText(_translate("MAINWINDOW", "Create Room"))
        self.actionJoin_Room.setText(_translate("MAINWINDOW", "Connect Room"))
        self.actionAbout.setText(_translate("MAINWINDOW", "About"))
        self.actionNormal.setText(_translate("MAINWINDOW", "Normal"))
        self.actionExit.setText(_translate("MAINWINDOW", "Exit"))
        self.actionTime.setText(_translate("MAINWINDOW", "Time"))
        self.actionSettings.setText(_translate("MAINWINDOW", "Settings"))
        self.actionBreak.setText(_translate("MAINWINDOW", "\n"
"Break "))

