# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\draxl\Desktop\Quardcard\MULTIPLAYER_ROOM_DIALOG.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Multiplayer_Setup(object):
    def setupUi(self, Multiplayer_Setup):
        Multiplayer_Setup.setObjectName("Multiplayer_Setup")
        Multiplayer_Setup.resize(432, 281)
        Multiplayer_Setup.setMinimumSize(QtCore.QSize(432, 281))
        Multiplayer_Setup.setMaximumSize(QtCore.QSize(432, 281))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 0, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 0, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 0, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 0, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 0, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 0, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 0, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 0, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 0, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Multiplayer_Setup.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        Multiplayer_Setup.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("multiplayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Multiplayer_Setup.setWindowIcon(icon)
        Multiplayer_Setup.setSizeGripEnabled(False)
        Multiplayer_Setup.setModal(False)
        self.btn_join = QtWidgets.QPushButton(Multiplayer_Setup)
        self.btn_join.setEnabled(True)
        self.btn_join.setGeometry(QtCore.QRect(360, 240, 61, 31))
        self.btn_join.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("dialog_ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_join.setIcon(icon1)
        self.btn_join.setIconSize(QtCore.QSize(16, 16))
        self.btn_join.setObjectName("btn_join")
        self.btn_close_right = QtWidgets.QPushButton(Multiplayer_Setup)
        self.btn_close_right.setEnabled(True)
        self.btn_close_right.setGeometry(QtCore.QRect(320, 240, 31, 31))
        self.btn_close_right.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_close_right.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("dialog_cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close_right.setIcon(icon2)
        self.btn_close_right.setIconSize(QtCore.QSize(16, 16))
        self.btn_close_right.setObjectName("btn_close_right")
        self.header = QtWidgets.QLabel(Multiplayer_Setup)
        self.header.setGeometry(QtCore.QRect(4, 10, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.header.setFont(font)
        self.header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.text = QtWidgets.QLabel(Multiplayer_Setup)
        self.text.setGeometry(QtCore.QRect(10, 70, 411, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text.setFont(font)
        self.text.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.text.setWordWrap(True)
        self.text.setOpenExternalLinks(True)
        self.text.setObjectName("text")
        self.line_1 = QtWidgets.QFrame(Multiplayer_Setup)
        self.line_1.setGeometry(QtCore.QRect(-70, 40, 581, 20))
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.line_2 = QtWidgets.QFrame(Multiplayer_Setup)
        self.line_2.setGeometry(QtCore.QRect(-70, 220, 581, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.room = QtWidgets.QLineEdit(Multiplayer_Setup)
        self.room.setGeometry(QtCore.QRect(20, 190, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.room.setFont(font)
        self.room.setMaxLength(6)
        self.room.setAlignment(QtCore.Qt.AlignCenter)
        self.room.setObjectName("room")
        self.name = QtWidgets.QLineEdit(Multiplayer_Setup)
        self.name.setGeometry(QtCore.QRect(140, 190, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setMaxLength(100)
        self.name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name.setObjectName("name")
        self.btn_picture = QtWidgets.QPushButton(Multiplayer_Setup)
        self.btn_picture.setGeometry(QtCore.QRect(100, 190, 31, 31))
        self.btn_picture.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pictures/bunny.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_picture.setIcon(icon3)
        self.btn_picture.setIconSize(QtCore.QSize(20, 20))
        self.btn_picture.setObjectName("btn_picture")
        self.firebase_URL = QtWidgets.QLineEdit(Multiplayer_Setup)
        self.firebase_URL.setGeometry(QtCore.QRect(20, 150, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.firebase_URL.setFont(font)
        self.firebase_URL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.firebase_URL.setObjectName("firebase_URL")
        self.btn_close_left = QtWidgets.QPushButton(Multiplayer_Setup)
        self.btn_close_left.setEnabled(True)
        self.btn_close_left.setGeometry(QtCore.QRect(10, 240, 31, 31))
        self.btn_close_left.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_close_left.setText("")
        self.btn_close_left.setIcon(icon2)
        self.btn_close_left.setIconSize(QtCore.QSize(16, 16))
        self.btn_close_left.setObjectName("btn_close_left")

        self.retranslateUi(Multiplayer_Setup)
        QtCore.QMetaObject.connectSlotsByName(Multiplayer_Setup)
        Multiplayer_Setup.setTabOrder(self.firebase_URL, self.room)
        Multiplayer_Setup.setTabOrder(self.room, self.btn_picture)
        Multiplayer_Setup.setTabOrder(self.btn_picture, self.name)
        Multiplayer_Setup.setTabOrder(self.name, self.btn_join)
        Multiplayer_Setup.setTabOrder(self.btn_join, self.btn_close_right)
        Multiplayer_Setup.setTabOrder(self.btn_close_right, self.btn_close_left)

    def retranslateUi(self, Multiplayer_Setup):
        _translate = QtCore.QCoreApplication.translate
        Multiplayer_Setup.setWindowTitle(_translate("Multiplayer_Setup", "Multiplayer Mode Setup"))
        self.btn_join.setText(_translate("Multiplayer_Setup", " Join"))
        self.header.setText(_translate("Multiplayer_Setup", "Multiplayer Mode"))
        self.text.setText(_translate("Multiplayer_Setup", "<p>In this mode you can connect with other friends and play with each other. You have to enter the Firebase URL of your host. Please refer to the README on <a href=\"https://github.com/ckoever/quardcard\">Github</a>.</p>"))
        self.room.setPlaceholderText(_translate("Multiplayer_Setup", "Room"))
        self.name.setPlaceholderText(_translate("Multiplayer_Setup", "Player Name"))
        self.firebase_URL.setPlaceholderText(_translate("Multiplayer_Setup", "Google Firebase Realtime Database URL"))

