# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\draxl\Desktop\Quardcard\OPTIONS_QUESTION_RADIO.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OPTIONS_QUESTION_RADIO(object):
    def setupUi(self, OPTIONS_QUESTION_RADIO):
        OPTIONS_QUESTION_RADIO.setObjectName("OPTIONS_QUESTION_RADIO")
        OPTIONS_QUESTION_RADIO.resize(640, 210)
        OPTIONS_QUESTION_RADIO.setMinimumSize(QtCore.QSize(640, 210))
        OPTIONS_QUESTION_RADIO.setMaximumSize(QtCore.QSize(640, 210))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        OPTIONS_QUESTION_RADIO.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        OPTIONS_QUESTION_RADIO.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("question_radio/question_radio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OPTIONS_QUESTION_RADIO.setWindowIcon(icon)
        self.save = QtWidgets.QPushButton(OPTIONS_QUESTION_RADIO)
        self.save.setEnabled(True)
        self.save.setGeometry(QtCore.QRect(560, 170, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.save.setFont(font)
        self.save.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("general/dialog_ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon1)
        self.save.setIconSize(QtCore.QSize(16, 16))
        self.save.setObjectName("save")
        self.answer_true_1 = QtWidgets.QRadioButton(OPTIONS_QUESTION_RADIO)
        self.answer_true_1.setGeometry(QtCore.QRect(10, 50, 41, 22))
        self.answer_true_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("general/answer_true.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.answer_true_1.setIcon(icon2)
        self.answer_true_1.setChecked(True)
        self.answer_true_1.setObjectName("answer_true_1")
        self.answer_text_1 = QtWidgets.QLineEdit(OPTIONS_QUESTION_RADIO)
        self.answer_text_1.setGeometry(QtCore.QRect(50, 50, 581, 24))
        self.answer_text_1.setText("")
        self.answer_text_1.setObjectName("answer_text_1")
        self.answer_true_2 = QtWidgets.QRadioButton(OPTIONS_QUESTION_RADIO)
        self.answer_true_2.setGeometry(QtCore.QRect(10, 80, 41, 22))
        self.answer_true_2.setText("")
        self.answer_true_2.setIcon(icon2)
        self.answer_true_2.setObjectName("answer_true_2")
        self.answer_text_2 = QtWidgets.QLineEdit(OPTIONS_QUESTION_RADIO)
        self.answer_text_2.setGeometry(QtCore.QRect(50, 80, 581, 24))
        self.answer_text_2.setText("")
        self.answer_text_2.setObjectName("answer_text_2")
        self.answer_true_3 = QtWidgets.QRadioButton(OPTIONS_QUESTION_RADIO)
        self.answer_true_3.setGeometry(QtCore.QRect(10, 110, 41, 22))
        self.answer_true_3.setText("")
        self.answer_true_3.setIcon(icon2)
        self.answer_true_3.setObjectName("answer_true_3")
        self.answer_text_3 = QtWidgets.QLineEdit(OPTIONS_QUESTION_RADIO)
        self.answer_text_3.setGeometry(QtCore.QRect(50, 110, 581, 24))
        self.answer_text_3.setText("")
        self.answer_text_3.setObjectName("answer_text_3")
        self.answer_true_4 = QtWidgets.QRadioButton(OPTIONS_QUESTION_RADIO)
        self.answer_true_4.setGeometry(QtCore.QRect(10, 140, 41, 22))
        self.answer_true_4.setText("")
        self.answer_true_4.setIcon(icon2)
        self.answer_true_4.setObjectName("answer_true_4")
        self.answer_text_4 = QtWidgets.QLineEdit(OPTIONS_QUESTION_RADIO)
        self.answer_text_4.setGeometry(QtCore.QRect(50, 140, 581, 24))
        self.answer_text_4.setText("")
        self.answer_text_4.setObjectName("answer_text_4")
        self.question = QtWidgets.QLineEdit(OPTIONS_QUESTION_RADIO)
        self.question.setGeometry(QtCore.QRect(10, 10, 621, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.question.setFont(font)
        self.question.setObjectName("question")

        self.retranslateUi(OPTIONS_QUESTION_RADIO)
        QtCore.QMetaObject.connectSlotsByName(OPTIONS_QUESTION_RADIO)
        OPTIONS_QUESTION_RADIO.setTabOrder(self.answer_true_1, self.answer_true_2)
        OPTIONS_QUESTION_RADIO.setTabOrder(self.answer_true_2, self.answer_true_3)
        OPTIONS_QUESTION_RADIO.setTabOrder(self.answer_true_3, self.answer_true_4)
        OPTIONS_QUESTION_RADIO.setTabOrder(self.answer_true_4, self.answer_text_1)
        OPTIONS_QUESTION_RADIO.setTabOrder(self.answer_text_1, self.answer_text_2)
        OPTIONS_QUESTION_RADIO.setTabOrder(self.answer_text_2, self.answer_text_3)
        OPTIONS_QUESTION_RADIO.setTabOrder(self.answer_text_3, self.answer_text_4)
        OPTIONS_QUESTION_RADIO.setTabOrder(self.answer_text_4, self.save)

    def retranslateUi(self, OPTIONS_QUESTION_RADIO):
        _translate = QtCore.QCoreApplication.translate
        OPTIONS_QUESTION_RADIO.setWindowTitle(_translate("OPTIONS_QUESTION_RADIO", "Options for Radio"))
        self.save.setText(_translate("OPTIONS_QUESTION_RADIO", " Save"))
        self.answer_true_1.setToolTip(_translate("OPTIONS_QUESTION_RADIO", "true answer"))
        self.answer_text_1.setToolTip(_translate("OPTIONS_QUESTION_RADIO", "item text"))
        self.answer_true_2.setToolTip(_translate("OPTIONS_QUESTION_RADIO", "true answer"))
        self.answer_text_2.setToolTip(_translate("OPTIONS_QUESTION_RADIO", "item text"))
        self.answer_true_3.setToolTip(_translate("OPTIONS_QUESTION_RADIO", "true answer"))
        self.answer_text_3.setToolTip(_translate("OPTIONS_QUESTION_RADIO", "item text"))
        self.answer_true_4.setToolTip(_translate("OPTIONS_QUESTION_RADIO", "true answer"))
        self.answer_text_4.setToolTip(_translate("OPTIONS_QUESTION_RADIO", "item text"))
        self.question.setPlaceholderText(_translate("OPTIONS_QUESTION_RADIO", "Question"))

