# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\draxl\Desktop\Quardcard\OPTIONS_QUESTION_MULTIPLE_CHOICE.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OPTIONS_MULTIPLE_CHOICE(object):
    def setupUi(self, OPTIONS_MULTIPLE_CHOICE):
        OPTIONS_MULTIPLE_CHOICE.setObjectName("OPTIONS_MULTIPLE_CHOICE")
        OPTIONS_MULTIPLE_CHOICE.resize(691, 331)
        OPTIONS_MULTIPLE_CHOICE.setMinimumSize(QtCore.QSize(691, 331))
        OPTIONS_MULTIPLE_CHOICE.setMaximumSize(QtCore.QSize(691, 331))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        OPTIONS_MULTIPLE_CHOICE.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        OPTIONS_MULTIPLE_CHOICE.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("question_multiple_choice/question_multiple_choice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OPTIONS_MULTIPLE_CHOICE.setWindowIcon(icon)
        self.save = QtWidgets.QPushButton(OPTIONS_MULTIPLE_CHOICE)
        self.save.setEnabled(True)
        self.save.setGeometry(QtCore.QRect(610, 290, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.save.setFont(font)
        self.save.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("general/dialog_ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon1)
        self.save.setIconSize(QtCore.QSize(16, 16))
        self.save.setObjectName("save")
        self.answer_text_1 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_1.setGeometry(QtCore.QRect(50, 50, 291, 24))
        self.answer_text_1.setText("")
        self.answer_text_1.setObjectName("answer_text_1")
        self.answer_true_3 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_3.setGeometry(QtCore.QRect(10, 80, 41, 22))
        self.answer_true_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("general/answer_true.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.answer_true_3.setIcon(icon2)
        self.answer_true_3.setChecked(False)
        self.answer_true_3.setObjectName("answer_true_3")
        self.answer_text_3 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_3.setGeometry(QtCore.QRect(50, 80, 291, 24))
        self.answer_text_3.setText("")
        self.answer_text_3.setObjectName("answer_text_3")
        self.answer_true_5 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_5.setGeometry(QtCore.QRect(10, 110, 41, 22))
        self.answer_true_5.setText("")
        self.answer_true_5.setIcon(icon2)
        self.answer_true_5.setObjectName("answer_true_5")
        self.answer_text_5 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_5.setGeometry(QtCore.QRect(50, 110, 291, 24))
        self.answer_text_5.setText("")
        self.answer_text_5.setObjectName("answer_text_5")
        self.answer_true_7 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_7.setGeometry(QtCore.QRect(10, 140, 41, 22))
        self.answer_true_7.setText("")
        self.answer_true_7.setIcon(icon2)
        self.answer_true_7.setChecked(False)
        self.answer_true_7.setObjectName("answer_true_7")
        self.answer_text_7 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_7.setGeometry(QtCore.QRect(50, 140, 291, 24))
        self.answer_text_7.setText("")
        self.answer_text_7.setObjectName("answer_text_7")
        self.answer_true_1 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_1.setGeometry(QtCore.QRect(10, 50, 41, 22))
        self.answer_true_1.setText("")
        self.answer_true_1.setIcon(icon2)
        self.answer_true_1.setObjectName("answer_true_1")
        self.answer_true_13 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_13.setGeometry(QtCore.QRect(10, 230, 41, 22))
        self.answer_true_13.setText("")
        self.answer_true_13.setIcon(icon2)
        self.answer_true_13.setChecked(False)
        self.answer_true_13.setObjectName("answer_true_13")
        self.answer_text_11 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_11.setGeometry(QtCore.QRect(50, 200, 291, 24))
        self.answer_text_11.setText("")
        self.answer_text_11.setObjectName("answer_text_11")
        self.answer_true_9 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_9.setGeometry(QtCore.QRect(10, 170, 41, 22))
        self.answer_true_9.setText("")
        self.answer_true_9.setIcon(icon2)
        self.answer_true_9.setChecked(False)
        self.answer_true_9.setObjectName("answer_true_9")
        self.answer_text_9 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_9.setGeometry(QtCore.QRect(50, 170, 291, 24))
        self.answer_text_9.setText("")
        self.answer_text_9.setObjectName("answer_text_9")
        self.answer_true_15 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_15.setGeometry(QtCore.QRect(10, 260, 41, 22))
        self.answer_true_15.setText("")
        self.answer_true_15.setIcon(icon2)
        self.answer_true_15.setChecked(False)
        self.answer_true_15.setObjectName("answer_true_15")
        self.answer_true_11 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_11.setGeometry(QtCore.QRect(10, 200, 41, 22))
        self.answer_true_11.setText("")
        self.answer_true_11.setIcon(icon2)
        self.answer_true_11.setChecked(False)
        self.answer_true_11.setObjectName("answer_true_11")
        self.answer_text_13 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_13.setGeometry(QtCore.QRect(50, 230, 291, 24))
        self.answer_text_13.setText("")
        self.answer_text_13.setObjectName("answer_text_13")
        self.answer_text_15 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_15.setGeometry(QtCore.QRect(50, 260, 291, 24))
        self.answer_text_15.setText("")
        self.answer_text_15.setObjectName("answer_text_15")
        self.answer_true_4 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_4.setGeometry(QtCore.QRect(350, 80, 41, 22))
        self.answer_true_4.setText("")
        self.answer_true_4.setIcon(icon2)
        self.answer_true_4.setChecked(False)
        self.answer_true_4.setObjectName("answer_true_4")
        self.answer_true_8 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_8.setGeometry(QtCore.QRect(350, 140, 41, 22))
        self.answer_true_8.setText("")
        self.answer_true_8.setIcon(icon2)
        self.answer_true_8.setChecked(False)
        self.answer_true_8.setObjectName("answer_true_8")
        self.answer_true_10 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_10.setGeometry(QtCore.QRect(350, 170, 41, 22))
        self.answer_true_10.setText("")
        self.answer_true_10.setIcon(icon2)
        self.answer_true_10.setChecked(False)
        self.answer_true_10.setObjectName("answer_true_10")
        self.answer_text_10 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_10.setGeometry(QtCore.QRect(390, 170, 291, 24))
        self.answer_text_10.setText("")
        self.answer_text_10.setObjectName("answer_text_10")
        self.answer_true_12 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_12.setGeometry(QtCore.QRect(350, 200, 41, 22))
        self.answer_true_12.setText("")
        self.answer_true_12.setIcon(icon2)
        self.answer_true_12.setChecked(False)
        self.answer_true_12.setObjectName("answer_true_12")
        self.answer_text_14 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_14.setGeometry(QtCore.QRect(390, 230, 291, 24))
        self.answer_text_14.setText("")
        self.answer_text_14.setObjectName("answer_text_14")
        self.answer_text_4 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_4.setGeometry(QtCore.QRect(390, 80, 291, 24))
        self.answer_text_4.setText("")
        self.answer_text_4.setObjectName("answer_text_4")
        self.answer_text_16 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_16.setGeometry(QtCore.QRect(390, 260, 291, 24))
        self.answer_text_16.setText("")
        self.answer_text_16.setObjectName("answer_text_16")
        self.answer_text_12 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_12.setGeometry(QtCore.QRect(390, 200, 291, 24))
        self.answer_text_12.setText("")
        self.answer_text_12.setObjectName("answer_text_12")
        self.answer_true_6 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_6.setGeometry(QtCore.QRect(350, 110, 41, 22))
        self.answer_true_6.setText("")
        self.answer_true_6.setIcon(icon2)
        self.answer_true_6.setChecked(False)
        self.answer_true_6.setObjectName("answer_true_6")
        self.answer_true_2 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_2.setGeometry(QtCore.QRect(350, 50, 41, 22))
        self.answer_true_2.setText("")
        self.answer_true_2.setIcon(icon2)
        self.answer_true_2.setChecked(False)
        self.answer_true_2.setObjectName("answer_true_2")
        self.answer_text_6 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_6.setGeometry(QtCore.QRect(390, 110, 291, 24))
        self.answer_text_6.setText("")
        self.answer_text_6.setObjectName("answer_text_6")
        self.answer_true_14 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_14.setGeometry(QtCore.QRect(350, 230, 41, 22))
        self.answer_true_14.setText("")
        self.answer_true_14.setIcon(icon2)
        self.answer_true_14.setChecked(False)
        self.answer_true_14.setObjectName("answer_true_14")
        self.answer_text_8 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_8.setGeometry(QtCore.QRect(390, 140, 291, 24))
        self.answer_text_8.setText("")
        self.answer_text_8.setObjectName("answer_text_8")
        self.answer_true_16 = QtWidgets.QCheckBox(OPTIONS_MULTIPLE_CHOICE)
        self.answer_true_16.setGeometry(QtCore.QRect(350, 260, 41, 22))
        self.answer_true_16.setText("")
        self.answer_true_16.setIcon(icon2)
        self.answer_true_16.setChecked(False)
        self.answer_true_16.setObjectName("answer_true_16")
        self.answer_text_2 = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.answer_text_2.setGeometry(QtCore.QRect(390, 50, 291, 24))
        self.answer_text_2.setText("")
        self.answer_text_2.setObjectName("answer_text_2")
        self.question = QtWidgets.QLineEdit(OPTIONS_MULTIPLE_CHOICE)
        self.question.setGeometry(QtCore.QRect(10, 10, 671, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.question.setFont(font)
        self.question.setObjectName("question")

        self.retranslateUi(OPTIONS_MULTIPLE_CHOICE)
        QtCore.QMetaObject.connectSlotsByName(OPTIONS_MULTIPLE_CHOICE)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.save, self.answer_text_1)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_1, self.answer_text_3)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_3, self.answer_text_5)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_5, self.answer_text_7)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_7, self.answer_text_9)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_9, self.answer_text_11)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_11, self.answer_text_13)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_13, self.answer_text_15)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_15, self.answer_text_2)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_2, self.answer_text_4)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_4, self.answer_text_6)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_6, self.answer_text_8)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_8, self.answer_text_10)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_10, self.answer_text_12)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_12, self.answer_text_14)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_14, self.answer_text_16)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_text_16, self.answer_true_1)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_1, self.answer_true_3)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_3, self.answer_true_5)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_5, self.answer_true_7)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_7, self.answer_true_9)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_9, self.answer_true_11)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_11, self.answer_true_13)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_13, self.answer_true_15)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_15, self.answer_true_2)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_2, self.answer_true_4)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_4, self.answer_true_6)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_6, self.question)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.question, self.answer_true_8)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_8, self.answer_true_10)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_10, self.answer_true_12)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_12, self.answer_true_14)
        OPTIONS_MULTIPLE_CHOICE.setTabOrder(self.answer_true_14, self.answer_true_16)

    def retranslateUi(self, OPTIONS_MULTIPLE_CHOICE):
        _translate = QtCore.QCoreApplication.translate
        OPTIONS_MULTIPLE_CHOICE.setWindowTitle(_translate("OPTIONS_MULTIPLE_CHOICE", "Options for Multiple Choice"))
        self.save.setText(_translate("OPTIONS_MULTIPLE_CHOICE", " Save"))
        self.answer_text_1.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_true_3.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "<html><head/><body><p>true answer</p></body></html>"))
        self.answer_text_3.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_true_5.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "<html><head/><body><p>true answer</p></body></html>"))
        self.answer_text_5.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_true_7.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "<html><head/><body><p>true answer</p></body></html>"))
        self.answer_text_7.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_true_1.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "<html><head/><body><p>true answer</p></body></html>"))
        self.answer_true_13.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "<html><head/><body><p>true answer</p></body></html>"))
        self.answer_text_11.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_true_9.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "<html><head/><body><p>true answer</p></body></html>"))
        self.answer_text_9.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_true_15.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "<html><head/><body><p>true answer</p></body></html>"))
        self.answer_true_11.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "<html><head/><body><p>true answer</p></body></html>"))
        self.answer_text_13.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_text_15.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_true_4.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "true answer"))
        self.answer_true_8.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "true answer"))
        self.answer_true_10.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "list item"))
        self.answer_text_10.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_true_12.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "true answer"))
        self.answer_text_14.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_text_4.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_text_16.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_text_12.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_true_6.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "true answer"))
        self.answer_true_2.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "list item"))
        self.answer_text_6.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_true_14.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "true answer"))
        self.answer_text_8.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.answer_true_16.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "true answer"))
        self.answer_text_2.setToolTip(_translate("OPTIONS_MULTIPLE_CHOICE", "item text"))
        self.question.setPlaceholderText(_translate("OPTIONS_MULTIPLE_CHOICE", "Question"))

